version: "3"

services:
  bot:
    build: 
      context: .
      dockerfile: ./bot/Dockerfile
    depends_on:
      - dbservice
    ports:
      - 443:443
      - 80:80
      - 5222:5222

  dbservice:
    build: 
      context: .
      dockerfile: ./dbservice/Dockerfile
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: postgres


