version: "3"

services:
  bot:
    build: bot/
    depends_on:
      - dbservice
    ports:
      - 443:443

  dbservice:
    build: dbservice/
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: postgres
    ports:
      - 5432:5432


